### ISSUE TITLE
[Create a bootable USB stick on macOS] Catalina X Etcher

### ISSUE THREAD

**Issue by denizboz** [canonical-web-and-design/tutorials.ubuntu.com#1070]
Etcher does not work properly on Catalina. You should post and alternative way to do it, such as via mac terminal.

**Comment by janbildsoehansen** [comment]
i have the same issue cant make a new bootable usb

**Comment by MortenVinding** [comment]
Wow I didn't even knew that!
I was just like: "MacOS must be able to do this without having to install any thing"

And it turned out it can: [https://www.lewan.com/blog/2012/02/10/making-a-bootable-usb-stick-on-an-apple-mac-os-x-from-an-iso](url)

I just followed that guide on my Mac with Catalina and it worked just perfect. No need to install anything at all 😉

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
