### ISSUE TITLE
Is it possible to make Snap Downloads more reliable ?

### ISSUE THREAD

**Issue by MansionsDave** [canonical-web-and-design/tutorials.ubuntu.com#1084]
Forgive me if my understanding of the matter is made up of some wild and inaccurate assumptions but from my understanding , PPA is Ubuntu's subset of Debian's "Aptitude" Repository and PPAs have their own download servers which perform really well .

Other than PPA , Ubuntu utilizes servers in a different way to enhance all their downloads , automatically assigning guests to their nearest server without the latter knowing about it .

So Ubuntu has ways of giving users download speeds that are beyond their actual download speeds , so why are Snap Downloads performing in an abysmal way ?

When I download a Snap I get a download speed which is not even 10% of my actual download speed and to make matters worse the download eventually fails .

From my understanding , Snap is projected to become Ubuntu's own Repository , no longer depending on Debian's Aptitude .

I understand that  Canonical is busy with making Snap work on Kernels outside of Unix , but let's also make better download reliability for Snap a priority too .

**Comment by timClicks** [comment]
Hi @MansionsDave this is important feedback, but it belongs on the [Snapcraft forums](https://forum.snapcraft.io/) rather than as an issue here. 

As an aside, you've mentioned reliability in the title of the issue.. but the body of the text refers to download speeds. Is reliability a problem?

As for the speed issue.. I think what you're encountering is that Ubuntu repositories have several mirrors, one of which will be much closer to you.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
