### ISSUE TITLE
Tutorials Wanted - Running Ubuntu desktop on AWS

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#455]
This tutorial will show the user how to run a full desktop version of Ubuntu on AWS EC2.

The tutorial should assume the reader already has an AWS account.
It should include installing the desktop packages, setting up a vnc or remote dektop server, and configuring access for that with the AWS firewall, and finally connecting to the instance via another desktop.

**Comment by undef314** [comment]
@evilnick - I have done this task by setting up an AWS-EC2.
I used terminal on a mac to SSH into the machine after setting up the inbound rules, and finally I used VNC to access the Ubuntu Desktop.

I cannot claim this task on the google code in website since my previous task is under review.
Still, I'll start writing the tutorial.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
