### ISSUE TITLE
Sugestion, on install ubuntu tutorial with pen drive

### ISSUE THREAD

**Issue by pedroth** [canonical-web-and-design/tutorials.ubuntu.com#836]
On page of of the install [Ubuntu  tutorial](https://tutorials.ubuntu.com/tutorial/tutorial-install-ubuntu-desktop#3), there should be a link to the create [bootable pen] (https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-ubuntu#0) tutorial.

Thank you

**Comment by Zesupermatou** [comment]
I agree, just had the same thought while going through the tutorial on how to install ubuntu on desktop.  I got stuck on step 4 because I didnt know I had to do something to my usb drive to make it bootable. Then I found online I could use Etcher to do that, and that definitly should be in the tutorial.

**Comment by pmahnke** [comment]
@Zesupermatou good reccomendtion, we will update for accordingly next time we update this.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
